#!/usr/bin/env python3
"""
Recalculate DG progress reports from pasted text blocks or AGA full-report workbooks.

In interactive mode, the script expects:
  1. The previous formatted report, or an empty block for a first report.
  2. One current rack-level output for each DG in the previous report.
     The default AGA flow is DG1 through DG5.

It uses the previous report's Current column as the new Previous column, then
uses the rack-level DG outputs as the new Current values.

Workbook mode reads one or more T0 qcli *_full_report.xlsx files, groups rows
by the AGA5 DG rack mapping, and builds the same T0 <> T1 progress report. In
workbook mode the combined_fec_with_pp sheet is split from the row values:
  - FEC bin 7 through 15 in Lock Status counts as Fec Bin
  - Pre-FEC BER greater than 1e-7 counts as Pre Fec
  - Combined FEC remains the row count

The T1 <> T0 compact Excel artifact generated by this script is built from the
same workbook rows read by this script; it does not import or call
aga52_final_ppforall.py.

T1-side source workbooks from aga52_final_ppforall.py, such as RX power,
Pre-FEC, and FEC Bin *_full_report.xlsx files, are intentionally rejected as
input here. Compact those in aga52_final_ppforall.py instead, then optionally
pass the compact AGA5.2-DG...with-pp.xlsx workbook via --t1-report.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from copy import copy
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple


TARGET_RE = re.compile(r"DG\d+", re.IGNORECASE)
TOTAL_TARGET = "TOTAL"
ISSUE_METRICS = ("LLDP", "Interface", "Optics TX/RX", "Pre Fec", "Fec Bin", "Combined FEC")
METRICS = (*ISSUE_METRICS, "Total")
COMPARISON_HEADERS = ("Target", "Previous", "Current", "Absolute", "Progress %")
OPTICS_FEC_KEYS = ("RX Optics", "TX Optics", "Fec Bin", "Pre-FEC")
PRE_FEC_BER_THRESHOLD = 1e-7
FEC_BIN_MIN = 7
FEC_BIN_MAX = 15
NON_IPR_RELAX_RX_MIN_DBM = -4.0
NON_IPR_RELAX_TX_MIN_DBM = -1.0
NON_IPR_RELAX_MAX_DBM = 5.5
IPR_RELAX_RX_MIN_DBM = -5.0
IPR_RELAX_TX_MIN_DBM = -3.0
IPR_RELAX_MAX_DBM = 3.0
FLOAT_RE = re.compile(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?")
FEC_BIN_COUNT_RE = re.compile(
    r"FEC[_\s-]*BIN[_\s-]*(\d+)[_\s-]*COUNT\s*=\s*([-+]?\d+)",
    re.IGNORECASE,
)
FEC_BIN_RE = re.compile(r"FEC[_\s-]*BIN[_\s-]*(\d+)", re.IGNORECASE)
DEFAULT_DATA_DIR = Path("~/qclihcdata/aga").expanduser()
DEFAULT_PREVIOUS_REPORT = DEFAULT_DATA_DIR / "previous.txt"
DEFAULT_T1_T0_STYLE_TEMPLATE = (
    DEFAULT_DATA_DIR
    / "AGA5.2-DG9-10-15-16-25-26-t1-t0-rx-tx-prefec-fecbin-2026-05-31-1932-with-pp.xlsx"
)
DEFAULT_COMBINED_FEC_STYLE_TEMPLATE = (
    DEFAULT_DATA_DIR / "aga5_q2_t0_t1_combined_fec_by_dg_template.xlsx"
)

DG_RACKS: Dict[str, Tuple[str, ...]] = {
    "DG1": ("5031", "5131"),
    "DG2": ("5034", "5134"),
    "DG3": ("5033", "5133"),
    "DG4": ("5032", "5132"),
    "DG5": ("5006", "5106"),
    "DG6": ("5003", "5103"),
    "DG7": ("5004", "5104"),
    "DG8": ("5005", "5105"),
    "DG9": ("6539", "6631"),
    "DG10": ("6542", "6634"),
    "DG11": ("6541", "6633"),
    "DG12": ("6540", "6632"),
    "DG13": ("6506", "6606"),
    "DG14": ("6503", "6603"),
    "DG15": ("6504", "6604"),
    "DG16": ("6505", "6605"),
    "DG17": ("8031", "8131"),
    "DG18": ("8034", "8134"),
    "DG19": ("8033", "8133"),
    "DG20": ("8032", "8132"),
    "DG21": ("8006", "8106"),
    "DG22": ("8003", "8103"),
    "DG23": ("8004", "8104"),
    "DG24": ("8005", "8105"),
    "DG25": ("5430", "5530"),
    "DG26": ("5429", "5529"),
    "DG27": ("8429", "8529"),
    "DG28": ("5431", "5531"),
    "DG29": ("6524", "6624"),
}
ATOM_INSTANCE_TARGETS = frozenset({"DG6", "DG11", "DG12", "DG15", "DG21", "DG22", "DG25"})
DEFAULT_QCLI_INSTANCE = 3
ATOM_QCLI_INSTANCE = 3
ALL_DG_TARGETS: Tuple[str, ...] = tuple(DG_RACKS)
RACK_TO_DG: Dict[str, str] = {
    rack: target for target, racks in DG_RACKS.items() for rack in racks
}

EXCEL_METRIC_SHEETS = (
    ("full_path_lldp_with_int_down", "LLDP"),
    ("interfaces_sp_with_pp", "Interface"),
    ("optics_rx_tx_threshold_with_pp", "Optics TX/RX"),
    ("combined_fec_with_pp", "Combined FEC"),
)
T1_SIDE_SOURCE_PREFIXES = (
    ("T1 -_ T0 RX power", "RX power"),
    ("Pre Fec Ber issues T1 ", "Pre-FEC"),
    ("Fec Bin issues T1 -_ T0 ", "FEC Bin"),
)


def racks_for_targets(targets: Sequence[str]) -> List[str]:
    racks: List[str] = []
    for target in targets:
        if target not in DG_RACKS:
            raise ValueError(f"No rack mapping exists for {target}")
        for rack in DG_RACKS[target]:
            if rack not in racks:
                racks.append(rack)
    return racks


def qcli_instance_for_target(target: str) -> int:
    return ATOM_QCLI_INSTANCE if target in ATOM_INSTANCE_TARGETS else DEFAULT_QCLI_INSTANCE


def qcli_command_for_targets(targets: Sequence[str], instance: int, relax: bool = False) -> str:
    dg_numbers: List[str] = []
    for target in targets:
        if target not in DG_RACKS:
            raise ValueError(f"No rack mapping exists for {target}")
        dg_numbers.append(str(int(target.removeprefix("DG"))))
    dg_list = ",".join(dg_numbers)
    relax_flag = " --optics-relax" if relax else ""
    return (
        f"qcli hc-summary --region aga --building 5 --instance {instance} --state deployed "
        f"--spectrum --customtag test_spectrum_fec_ber --failures-only --filter_pg --t1-reports --nvidia-linkflap-clear --slack{relax_flag} --deployment-group {dg_list}"
    )


def combined_qcli_command(targets: Sequence[str], relax: bool = False) -> str:
    targets_by_instance: Dict[int, List[str]] = {}
    for target in targets:
        instance = qcli_instance_for_target(target)
        targets_by_instance.setdefault(instance, []).append(target)
    return "\n".join(
        qcli_command_for_targets(instance_targets, instance, relax)
        for instance, instance_targets in targets_by_instance.items()
    )


def normalize(value: object) -> str:
    return re.sub(r"[^a-z0-9]+", "", str(value).strip().lower())


def t1_side_source_report_kind(path: Path) -> str | None:
    compact_name = " ".join(path.name.split())
    for prefix, kind in T1_SIDE_SOURCE_PREFIXES:
        if compact_name.startswith(prefix):
            return kind
    return None


def reject_t1_side_source_report(path: Path, option_name: str) -> None:
    report_kind = t1_side_source_report_kind(path)
    if report_kind is None:
        return
    raise ValueError(
        f"{path.name} is a T1-side {report_kind} source full_report. "
        f"Do not pass these files to {option_name} in aga_dg_report_recalculator.py. "
        "Use the combined T0 qcli full_report for this script; compact T1-side "
        "RX/Pre-FEC/FEC-Bin files with aga52_final_ppforall.py instead."
    )


def parse_int(value: object) -> int:
    text = str(value).replace(",", "").strip()
    match = re.search(r"[-+]?\d+", text)
    if not match:
        raise ValueError(f"Expected an integer value, got {value!r}")
    return int(match.group(0))


def parse_float_value(value: object) -> float | None:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).replace(",", "").strip()
    if not text:
        return None
    match = FLOAT_RE.search(text)
    if not match:
        return None
    try:
        return float(match.group(0))
    except ValueError:
        return None


def pre_fec_ber_over_threshold(value: object) -> bool:
    parsed = parse_float_value(value)
    return parsed is not None and parsed > PRE_FEC_BER_THRESHOLD


def lock_status_has_fec_bin_7_to_15(value: object) -> bool:
    text = str(value or "")
    matched_explicit_count = False
    for match in FEC_BIN_COUNT_RE.finditer(text):
        matched_explicit_count = True
        bin_num = int(match.group(1))
        count = int(match.group(2))
        if FEC_BIN_MIN <= bin_num <= FEC_BIN_MAX and count > 0:
            return True
    if matched_explicit_count:
        return False

    return any(
        FEC_BIN_MIN <= int(match.group(1)) <= FEC_BIN_MAX
        for match in FEC_BIN_RE.finditer(text)
    )


def is_lldp_interface_down_row(header: Sequence[str], row: Sequence[object]) -> bool:
    active_interface_idx = optional_column(
        header,
        ("Act. Interface", "Active Interface", "Interface Status"),
    )
    if active_interface_idx is None or active_interface_idx >= len(row):
        return False
    return normalize(row[active_interface_idx]) == "interfacedown"


def split_pipe_row(line: str) -> List[str] | None:
    stripped = line.strip()
    if not stripped.startswith("|") or not stripped.endswith("|"):
        return None
    return [cell.strip() for cell in stripped.strip("|").split("|")]


def is_border(line: str) -> bool:
    stripped = line.strip()
    return bool(stripped) and set(stripped) <= {"+", "-"}


def metric_name(raw: str) -> str | None:
    aliases = {
        "lldp": "LLDP",
        "interface": "Interface",
        "interfacedown": "Interface",
        "opticstxrx": "Optics TX/RX",
        "optics": "Optics TX/RX",
        "prefec": "Pre Fec",
        "prefecber": "Pre Fec",
        "fecbin": "Fec Bin",
        "fecbinissues": "Fec Bin",
        "combinedfec": "Combined FEC",
        "fec": "Combined FEC",
        "total": "Total",
    }
    return aliases.get(normalize(raw))


def find_column(header: Sequence[str], candidates: Iterable[str]) -> int:
    normalized = [normalize(col) for col in header]
    for candidate in candidates:
        candidate_norm = normalize(candidate)
        if candidate_norm in normalized:
            return normalized.index(candidate_norm)
    raise ValueError(f"Missing required column. Header was: {header}")


def optional_column(header: Sequence[str], candidates: Iterable[str]) -> int | None:
    try:
        return find_column(header, candidates)
    except ValueError:
        return None


def first_metric_table_after(lines: Sequence[str], start_idx: int) -> Dict[str, int]:
    for idx in range(start_idx, len(lines)):
        row = split_pipe_row(lines[idx])
        if not row:
            continue

        try:
            current_idx = find_column(row, ("Current",))
            first_row = idx + 1
        except ValueError:
            current_idx = 2
            first_row = idx

        parsed: Dict[str, int] = {}

        for row_line in lines[first_row:]:
            if is_border(row_line):
                continue

            row = split_pipe_row(row_line)
            if row is None:
                if parsed:
                    break
                continue

            name = metric_name(row[0])
            if name and current_idx < len(row):
                parsed[name] = parse_int(row[current_idx])

        if parsed:
            return {metric: parsed.get(metric, 0) for metric in METRICS}

    return {}


def normalize_target(raw: str) -> str:
    text = str(raw).strip().upper()
    match = re.fullmatch(r"(?:DG|PG)?\s*(\d+)", text)
    if not match:
        raise ValueError(f"Invalid DG target {raw!r}; expected values like DG1 or DG4")
    return f"DG{int(match.group(1))}"


def parse_target_list(raw: str | None) -> List[str] | None:
    if not raw:
        return None

    targets: List[str] = []
    for item in raw.split(","):
        item = item.strip()
        if not item:
            continue
        if item.lower() == "all":
            for target in ALL_DG_TARGETS:
                if target not in targets:
                    targets.append(target)
            continue

        target = normalize_target(item)
        if target not in targets:
            targets.append(target)

    if not targets:
        raise ValueError("No valid targets were provided")
    return targets


def discover_targets(lines: Sequence[str]) -> List[str]:
    targets: List[str] = []

    for line in lines:
        row = split_pipe_row(line)
        if row:
            candidate = row[0].strip().upper()
        else:
            candidate = line.strip().upper()

        if TARGET_RE.fullmatch(candidate) and candidate not in targets:
            targets.append(candidate)

    return targets


def previous_current_metrics(
    previous_report: str,
    targets: Sequence[str] | None = None,
    allow_missing: bool = False,
) -> Tuple[Dict[str, Dict[str, int]], List[str]]:
    lines = previous_report.splitlines()
    selected_targets = list(targets) if targets is not None else discover_targets(lines)
    if not selected_targets:
        if allow_missing:
            return {}, []
        raise ValueError("Could not find any DG metric tables in the previous report")

    result: Dict[str, Dict[str, int]] = {}

    for target in selected_targets:
        for idx, line in enumerate(lines):
            if line.strip().upper() == target:
                table = first_metric_table_after(lines, idx + 1)
                if table:
                    result[target] = table
                    break

        if target not in result and not allow_missing:
            raise ValueError(f"Could not find the {target} metric table in the previous report")

    found_targets = [target for target in selected_targets if target in result]
    result[TOTAL_TARGET] = sum_metrics(*(result[target] for target in found_targets))
    return result, selected_targets


def fill_missing_previous_from_current(
    previous: Dict[str, Dict[str, int]],
    current: Dict[str, Dict[str, int]],
    targets: Sequence[str],
) -> None:
    for target in targets:
        current.setdefault(target, empty_metric_counts())
        previous.setdefault(target, dict(current[target]))


def parse_rack_rollup(current_output: str, target: str) -> Tuple[Dict[str, int], List[str]]:
    lines = current_output.splitlines()
    warnings: List[str] = []

    for idx, line in enumerate(lines):
        header = split_pipe_row(line)
        if not header or normalize(header[0]) != "rack":
            continue

        lldp_idx = find_column(header, ("LLDP",))
        interface_idx = find_column(header, ("INTERFACEDOWN", "InterfaceDown", "Interface"))
        optics_idx = find_column(header, ("OPTICS", "Optics TX/RX"))
        fec_idx = find_column(header, ("COMBINED FEC", "FEC"))
        total_idx = None
        try:
            total_idx = find_column(header, ("TOTAL", "Total"))
        except ValueError:
            pass

        totals = {
            "LLDP": 0,
            "Interface": 0,
            "Optics TX/RX": 0,
            "Pre Fec": 0,
            "Fec Bin": 0,
            "Combined FEC": 0,
            "Total": 0,
        }
        saw_rack = False

        for row_line in lines[idx + 1 :]:
            if is_border(row_line):
                continue

            row = split_pipe_row(row_line)
            if row is None:
                if saw_rack:
                    break
                continue

            rack = row[0].strip()
            rack_norm = normalize(rack)
            if rack_norm == "total":
                continue
            if not re.fullmatch(r"\d+", rack):
                if saw_rack:
                    break
                continue

            saw_rack = True
            lldp = parse_int(row[lldp_idx])
            interface = parse_int(row[interface_idx])
            optics = parse_int(row[optics_idx])
            fec = parse_int(row[fec_idx])
            calculated_total = lldp + interface + optics + fec

            if total_idx is not None and total_idx < len(row):
                printed_total = parse_int(row[total_idx])
                if printed_total != calculated_total:
                    warnings.append(
                        f"{target} rack {rack}: printed total {printed_total} "
                        f"does not match metric sum {calculated_total}"
                    )

            totals["LLDP"] += lldp
            totals["Interface"] += interface
            totals["Optics TX/RX"] += optics
            totals["Combined FEC"] += fec
            totals["Total"] += calculated_total

        if saw_rack:
            return totals, warnings

    raise ValueError(f"Could not find a rack roll-up table in the {target} input")


def optics_fec_from_values(values: Sequence[int]) -> Dict[str, int]:
    if len(values) >= 5 and values[4] == values[0] + values[1] + values[2] + values[3]:
        rx_optics, tx_optics, fec_bin, pre_fec = values[0], values[1], values[2], values[3]
    elif (
        len(values) >= 5
        and values[2] == values[0] + values[1]
        and values[4] == values[2] + values[3]
    ):
        rx_optics, tx_optics, fec_bin, pre_fec = values[0], values[1], 0, values[3]
    elif len(values) >= 4:
        rx_optics, tx_optics, fec_bin, pre_fec = values[0], values[1], values[2], values[3]
    elif len(values) >= 3:
        rx_optics, tx_optics, fec_bin, pre_fec = values[0], values[1], 0, values[2]
    else:
        raise ValueError("Expected RX optics, TX optics, FEC BIN, and Pre-FEC values")

    return {
        "RX Optics": rx_optics,
        "TX Optics": tx_optics,
        "Fec Bin": fec_bin,
        "Pre-FEC": pre_fec,
    }


def parse_optics_fec_line(line: str, targets: Sequence[str]) -> Tuple[str, Dict[str, int]] | None:
    target_set = set(targets)
    row = split_pipe_row(line)

    if row:
        target = row[0].strip().upper()
        if target == "TOTAL":
            return None
        if target in target_set:
            values = [parse_int(cell) for cell in row[1:] if re.search(r"[-+]?\d+", cell)]
            return target, optics_fec_from_values(values)
        return None

    match = TARGET_RE.search(line)
    if not match:
        return None

    target = match.group(0).upper()
    if target not in target_set:
        return None

    value_text = f"{line[:match.start()]} {line[match.end():]}"
    values = [int(value) for value in re.findall(r"[-+]?\d+", value_text.replace(",", ""))]
    return target, optics_fec_from_values(values)


def parse_optics_fec_block(text: str, targets: Sequence[str]) -> Dict[str, Dict[str, int]]:
    lines = text.splitlines()
    target_set = set(targets)
    parsed: Dict[str, Dict[str, int]] = {}

    for idx, line in enumerate(lines):
        header = split_pipe_row(line)
        if not header:
            continue

        try:
            target_idx = find_column(header, ("DG", "Target"))
            rx_idx = find_column(header, ("RX Optics", "Rx Optics", "RX"))
            tx_idx = find_column(header, ("TX Optics", "Tx Optics", "TX"))
            fecbin_idx = optional_column(header, ("FEC BIN", "Fec Bin", "FECBin"))
            prefec_idx = find_column(header, ("Pre-FEC", "Pre FEC", "PreFEC"))
        except ValueError:
            continue

        for row_line in lines[idx + 1 :]:
            if is_border(row_line):
                continue

            row = split_pipe_row(row_line)
            if row is None:
                break

            target = row[target_idx].strip().upper()
            if target == "TOTAL":
                continue
            if target not in target_set:
                continue

            parsed[target] = {
                "RX Optics": parse_int(row[rx_idx]),
                "TX Optics": parse_int(row[tx_idx]),
                "Fec Bin": parse_int(row[fecbin_idx]) if fecbin_idx is not None else 0,
                "Pre-FEC": parse_int(row[prefec_idx]),
            }

    for line in lines:
        parsed_line = parse_optics_fec_line(line, targets)
        if parsed_line:
            target, counts = parsed_line
            parsed[target] = counts

    return parsed


def read_optics_fec_counts(targets: Sequence[str], sentinel: str) -> Dict[str, Dict[str, int]]:
    print(
        "\nPaste RX optics, TX optics, FEC BIN, and Pre-FEC counts for "
        f"{', '.join(targets)}. Use rows like 'DG5 37 0 4 8', or paste a table "
        f"with DG/RX Optics/TX Optics/FEC BIN/Pre-FEC columns. Finish with {sentinel!r}; "
        f"enter {sentinel!r} immediately to skip.",
        file=sys.stderr,
    )
    lines: List[str] = []
    while True:
        try:
            line = input()
        except EOFError as exc:
            raise SystemExit(
                f"Input ended before sentinel {sentinel!r} for optics/FEC counts"
            ) from exc
        if line.strip() == sentinel:
            break
        lines.append(line)

    text = "\n".join(lines)
    if not text.strip():
        return {}
    return parse_optics_fec_block(text, targets)


def optics_fec_counts(args: argparse.Namespace, targets: Sequence[str]) -> Dict[str, Dict[str, int]]:
    if args.no_optics_fec_summary:
        return {}

    counts: Dict[str, Dict[str, int]] = {}

    if args.optics_fec_file:
        counts.update(
            parse_optics_fec_block(
                Path(args.optics_fec_file).read_text(encoding="utf-8"),
                targets,
            )
        )

    for item in args.optics_fec or []:
        parsed = parse_optics_fec_line(item, targets)
        if not parsed:
            raise ValueError(
                f"Invalid --optics-fec value {item!r}; expected DG=RX,TX,FECBIN,PRE or DG RX TX FECBIN PRE"
            )
        target, target_counts = parsed
        counts[target] = target_counts

    missing = [target for target in targets if target not in counts]
    if missing:
        counts.update(read_optics_fec_counts(missing, args.sentinel))

    if not counts:
        return {}

    missing = [target for target in targets if target not in counts]
    if missing:
        raise ValueError(
            "Missing optics/FEC counts for: "
            f"{', '.join(missing)}"
        )

    return {target: counts[target] for target in targets}


def sum_metrics(*items: Dict[str, int]) -> Dict[str, int]:
    return {metric: sum(item.get(metric, 0) for item in items) for metric in METRICS}


def progress(previous: int, current: int) -> str:
    if previous == 0:
        if current == 0:
            return "0.0%"
        return "N/A"

    pct = ((previous - current) / previous) * 100
    return f"{pct:+.1f}%"


def signed_int(value: int) -> str:
    return f"+{value}" if value > 0 else str(value)


def table(
    headers: Sequence[str] | None,
    rows: Sequence[Sequence[object]],
    left_columns: set[int],
    min_widths: Sequence[int] | None = None,
) -> str:
    string_rows = [[str(cell) for cell in row] for row in rows]
    column_count = len(headers) if headers is not None else (len(string_rows[0]) if string_rows else 0)
    widths = [
        max(
            len(str(headers[col])) if headers is not None else 0,
            min_widths[col] if min_widths is not None and col < len(min_widths) else 0,
            *(len(row[col]) for row in string_rows),
        )
        for col in range(column_count)
    ]

    border = "+" + "+".join("-" * (width + 2) for width in widths) + "+"

    def render_row(cells: Sequence[object]) -> str:
        rendered = []
        for col, cell in enumerate(cells):
            text = str(cell)
            if col in left_columns:
                rendered.append(f" {text:<{widths[col]}} ")
            else:
                rendered.append(f" {text:>{widths[col]}} ")
        return "|" + "|".join(rendered) + "|"

    output = [border]
    if headers is not None:
        output.extend([render_row(headers), border])
    output.extend(render_row(row) for row in rows)
    output.append(border)
    return "\n".join(output)


def metric_rows(previous: Dict[str, int], current: Dict[str, int]) -> List[List[object]]:
    rows: List[List[object]] = []
    for metric in METRICS:
        prev = previous.get(metric, 0)
        cur = current.get(metric, 0)
        rows.append([metric, prev, cur, signed_int(cur - prev), progress(prev, cur)])
    return rows


def optics_fec_rows(counts: Dict[str, Dict[str, int]], targets: Sequence[str]) -> List[List[object]]:
    rows: List[List[object]] = []
    totals = {key: 0 for key in OPTICS_FEC_KEYS}

    for target in targets:
        target_counts = counts.get(target, {})
        rx_optics = target_counts.get("RX Optics", 0)
        tx_optics = target_counts.get("TX Optics", 0)
        fec_bin = target_counts.get("Fec Bin", 0)
        pre_fec = target_counts.get("Pre-FEC", 0)
        grand_total = rx_optics + tx_optics + fec_bin + pre_fec

        totals["RX Optics"] += rx_optics
        totals["TX Optics"] += tx_optics
        totals["Fec Bin"] += fec_bin
        totals["Pre-FEC"] += pre_fec
        rows.append([target, rx_optics, tx_optics, fec_bin, pre_fec, grand_total])

    grand_total = (
        totals["RX Optics"]
        + totals["TX Optics"]
        + totals["Fec Bin"]
        + totals["Pre-FEC"]
    )
    rows.append(
        [
            "Total",
            totals["RX Optics"],
            totals["TX Optics"],
            totals["Fec Bin"],
            totals["Pre-FEC"],
            grand_total,
        ]
    )
    return rows


def sort_key_target(target: str) -> Tuple[int, int | str]:
    match = re.fullmatch(r"DG(\d+)", target.upper())
    if match:
        return (0, int(match.group(1)))
    if target.upper() == TOTAL_TARGET:
        return (2, target)
    return (1, target)


def rack_key(value: object) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    match = re.search(r"(\d{4})", text)
    return match.group(1) if match else None


def row_dict(header: Sequence[str], row: Sequence[object]) -> Dict[str, object]:
    return {
        str(name).strip() if name is not None else f"Column {idx + 1}": (
            row[idx] if idx < len(row) else None
        )
        for idx, name in enumerate(header)
    }


def target_for_excel_row(header: Sequence[str], row: Sequence[object]) -> str | None:
    rack_idx = optional_column(header, ("Rack", "DeviceA_Rack", "rack_a"))
    if rack_idx is None or rack_idx >= len(row):
        return None
    rack = rack_key(row[rack_idx])
    if not rack:
        return None
    return RACK_TO_DG.get(rack)


def empty_metric_counts() -> Dict[str, int]:
    return {metric: 0 for metric in METRICS}


def read_excel_current(
    paths: Sequence[Path],
    targets: Sequence[str] | None = None,
    relax: bool = False,
    relax_ipr: bool = False,
) -> Tuple[Dict[str, Dict[str, int]], List[str], List[Dict[str, object]]]:
    try:
        from openpyxl import load_workbook
    except ImportError as exc:
        raise RuntimeError("Workbook mode requires openpyxl") from exc

    target_filter = set(targets) if targets else None
    current: Dict[str, Dict[str, int]] = defaultdict(empty_metric_counts)
    details: List[Dict[str, object]] = []

    for raw_path in paths:
        path = raw_path.expanduser()
        reject_t1_side_source_report(path, "--excel/--full-report")
        if not path.exists():
            raise FileNotFoundError(path)
        wb = load_workbook(path, read_only=True, data_only=True)

        for sheet_name, metric in EXCEL_METRIC_SHEETS:
            if sheet_name not in wb.sheetnames:
                continue
            ws = wb[sheet_name]
            rows = ws.iter_rows(values_only=True)
            try:
                header = [str(value).strip() if value is not None else "" for value in next(rows)]
            except StopIteration:
                continue

            lock_idx = optional_column(header, ("Lock Status", "Lock_status", "LockStatus"))
            pre_fec_ber_idx = optional_column(
                header,
                (
                    "Pre-FEC BER",
                    "Pre FEC BER",
                    "Pre‑FEC BER",
                    "Pre_FEC_BER",
                    "RAW BER",
                    "RAW_BER",
                    "RAW_BER_MAX",
                ),
            )

            for row in rows:
                target = target_for_excel_row(header, row)
                if target is None:
                    continue
                if target_filter is not None and target not in target_filter:
                    continue
                if metric == "LLDP" and is_lldp_interface_down_row(header, row):
                    continue
                original = row_dict(header, row)
                if metric == "Optics TX/RX" and not optics_row_passes_relaxed_threshold(
                    original,
                    relax=relax,
                    relax_ipr=relax_ipr,
                ):
                    continue

                counts_fec_bin = 0
                counts_pre_fec = 0
                current[target][metric] += 1

                if metric == "Combined FEC":
                    lock_status = ""
                    if lock_idx is not None and lock_idx < len(row):
                        lock_status = str(row[lock_idx] or "")

                    pre_fec_ber = None
                    if pre_fec_ber_idx is not None and pre_fec_ber_idx < len(row):
                        pre_fec_ber = row[pre_fec_ber_idx]

                    if lock_status_has_fec_bin_7_to_15(lock_status):
                        current[target]["Fec Bin"] += 1
                        counts_fec_bin = 1
                    if pre_fec_ber_over_threshold(pre_fec_ber):
                        current[target]["Pre Fec"] += 1
                        counts_pre_fec = 1

                detail = {
                    "Source File": path.name,
                    "Source Sheet": sheet_name,
                    "DG": target,
                    "Issue Type": metric,
                    "Counts Fec Bin": counts_fec_bin,
                    "Counts Pre Fec": counts_pre_fec,
                }
                for key, value in original.items():
                    out_key = key if key not in detail else f"Original {key}"
                    detail[out_key] = value
                details.append(detail)

    if targets:
        selected_targets = list(targets)
        for target in selected_targets:
            current.setdefault(target, empty_metric_counts())
    else:
        selected_targets = sorted(current, key=sort_key_target)

    for values in current.values():
        values["Total"] = (
            values.get("LLDP", 0)
            + values.get("Interface", 0)
            + values.get("Optics TX/RX", 0)
            + values.get("Combined FEC", 0)
        )

    return dict(current), selected_targets, details


def unique_columns(rows: Sequence[Dict[str, object]]) -> List[str]:
    columns: List[str] = []
    for row in rows:
        for key in row:
            if key not in columns:
                columns.append(key)
    return columns


def safe_sheet_name(name: str, used: set[str]) -> str:
    cleaned = re.sub(r"[\[\]:*?/\\]", "_", name)[:31] or "Sheet"
    candidate = cleaned
    counter = 1
    while candidate in used:
        suffix = f"_{counter}"
        candidate = f"{cleaned[:31 - len(suffix)]}{suffix}"
        counter += 1
    used.add(candidate)
    return candidate


def write_rows_sheet(
    wb,
    name: str,
    headers: Sequence[str],
    rows: Iterable[Sequence[object]],
    used: set[str],
):
    ws = wb.create_sheet(safe_sheet_name(name, used))
    ws.append(list(headers))
    for row in rows:
        ws.append(list(row))
    return ws


def write_detail_sheet(wb, name: str, rows: Sequence[Dict[str, object]], used: set[str]) -> None:
    headers = unique_columns(rows)
    ws = wb.create_sheet(safe_sheet_name(name, used))
    if headers:
        ws.append(headers)
        for row in rows:
            ws.append([row.get(header) for header in headers])


def first_sheet_matching(sheet_names: Sequence[str], pattern: str) -> str | None:
    compiled = re.compile(pattern)
    for sheet_name in sheet_names:
        if compiled.fullmatch(sheet_name):
            return sheet_name
    return None


def t1_t0_template_sheet_name(sheet_name: str, template_sheet_names: Sequence[str]) -> str | None:
    if sheet_name in template_sheet_names:
        return sheet_name
    if re.fullmatch(r"DG\d+", sheet_name):
        return first_sheet_matching(template_sheet_names, r"DG\d+")
    return None


def combined_fec_template_sheet_name(
    sheet_name: str,
    template_sheet_names: Sequence[str],
) -> str | None:
    if sheet_name in template_sheet_names:
        return sheet_name
    if re.fullmatch(r"DG\d+_combined_fec", sheet_name):
        return first_sheet_matching(template_sheet_names, r"DG\d+_combined_fec")
    return None


def copy_cell_format(source_cell, target_cell) -> None:
    if source_cell.has_style:
        target_cell._style = copy(source_cell._style)
    if source_cell.number_format:
        target_cell.number_format = source_cell.number_format
    target_cell.font = copy(source_cell.font)
    target_cell.fill = copy(source_cell.fill)
    target_cell.border = copy(source_cell.border)
    target_cell.alignment = copy(source_cell.alignment)
    target_cell.protection = copy(source_cell.protection)


def copy_dimension_format(source_ws, target_ws) -> None:
    for key, source_dim in source_ws.column_dimensions.items():
        target_dim = target_ws.column_dimensions[key]
        target_dim.width = source_dim.width
        target_dim.hidden = source_dim.hidden
        target_dim.outlineLevel = source_dim.outlineLevel
        target_dim.collapsed = source_dim.collapsed
        target_dim.bestFit = source_dim.bestFit

    for key, source_dim in source_ws.row_dimensions.items():
        target_dim = target_ws.row_dimensions[key]
        target_dim.height = source_dim.height
        target_dim.hidden = source_dim.hidden
        target_dim.outlineLevel = source_dim.outlineLevel
        target_dim.collapsed = source_dim.collapsed


def copy_sheet_format(source_ws, target_ws) -> None:
    from openpyxl.utils import get_column_letter

    copy_dimension_format(source_ws, target_ws)
    target_ws.freeze_panes = source_ws.freeze_panes
    target_ws.sheet_view.showGridLines = source_ws.sheet_view.showGridLines
    target_ws.sheet_format = copy(source_ws.sheet_format)
    target_ws.page_margins = copy(source_ws.page_margins)
    target_ws.page_setup = copy(source_ws.page_setup)
    target_ws.print_options = copy(source_ws.print_options)
    target_ws.sheet_properties.pageSetUpPr = copy(source_ws.sheet_properties.pageSetUpPr)
    target_ws.sheet_properties.outlinePr = copy(source_ws.sheet_properties.outlinePr)
    target_ws.sheet_properties.tabColor = copy(source_ws.sheet_properties.tabColor)

    if source_ws.auto_filter.ref and target_ws.max_row and target_ws.max_column:
        target_ws.auto_filter.ref = (
            f"A1:{get_column_letter(target_ws.max_column)}{target_ws.max_row}"
        )

    max_source_row = max(source_ws.max_row, 1)
    max_source_col = max(source_ws.max_column, 1)
    for row_idx in range(1, target_ws.max_row + 1):
        source_row_idx = min(row_idx, max_source_row)
        for col_idx in range(1, target_ws.max_column + 1):
            source_col_idx = min(col_idx, max_source_col)
            copy_cell_format(
                source_ws.cell(source_row_idx, source_col_idx),
                target_ws.cell(row_idx, col_idx),
            )


def apply_style_template(
    wb,
    template_path: Path,
    sheet_selector,
) -> None:
    template_path = template_path.expanduser()
    if not template_path.exists():
        return

    from openpyxl import load_workbook

    template_wb = load_workbook(template_path)
    template_sheet_names = template_wb.sheetnames
    for sheet_name in wb.sheetnames:
        template_sheet_name = sheet_selector(sheet_name, template_sheet_names)
        if template_sheet_name is None:
            continue
        copy_sheet_format(template_wb[template_sheet_name], wb[sheet_name])


def target_slug(targets: Sequence[str]) -> str:
    if tuple(targets) == ALL_DG_TARGETS:
        return "DGall"

    numbers: List[str] = []
    for target in targets:
        match = re.fullmatch(r"DG(\d+)", target.upper())
        numbers.append(match.group(1) if match else target.upper())
    return f"DG{'-'.join(numbers)}"


def timestamped_path(path: Path) -> Path:
    if not path.exists():
        return path

    counter = 1
    while True:
        candidate = path.with_name(f"{path.stem}_{counter}{path.suffix}")
        if not candidate.exists():
            return candidate
        counter += 1


def default_t1_t0_output_path(base_dir: Path, targets: Sequence[str], now: datetime) -> Path:
    return base_dir / (
        f"AGA5.2-{target_slug(targets)}-t1-t0-rx-tx-prefec-fecbin-"
        f"{now:%Y-%m-%d-%H%M}-with-pp.xlsx"
    )


def default_combined_fec_output_path(base_dir: Path, now: datetime) -> Path:
    return base_dir / f"aga5_q2_t0_t1_combined_fec_by_dg_{now:%Y%m%d_%H%M}.xlsx"


def has_pp(row: Dict[str, object]) -> bool:
    pp_a = str(row.get("PP_A") or "").strip()
    pp_z = str(row.get("PP_Z") or "").strip()
    missing = {"", "none", "nan", "pp_info_not_found"}
    return pp_a.lower() not in missing and pp_z.lower() not in missing


def optics_power_type(row: Dict[str, object]) -> str:
    power_type = normalize(row.get("Power Type", ""))
    if power_type in {"inputpower", "rx", "rxoptics"}:
        return "RX"
    if power_type in {"outputpower", "tx", "txoptics"}:
        return "TX"
    metric = normalize(row.get("Metric", ""))
    if metric in {"inputpower", "rx", "rxoptics"}:
        return "RX"
    if metric in {"outputpower", "tx", "txoptics"}:
        return "TX"
    return ""


def optics_measured_dbm(row: Dict[str, object]) -> float | None:
    candidates = (
        "Measured (dBm)",
        "Value",
        "RX power",
        "TX power",
        "Input Power",
        "Output Power",
        "Measured",
        "Power",
    )
    normalized = {normalize(key): value for key, value in row.items()}
    for column in candidates:
        value = row.get(column, normalized.get(normalize(column)))
        measured = parse_float_value(value)
        if measured is not None:
            return measured
    return None


def optics_row_passes_relaxed_threshold(
    row: Dict[str, object],
    *,
    relax: bool = False,
    relax_ipr: bool = False,
    is_ipr: bool = False,
) -> bool:
    if is_ipr:
        if not relax_ipr:
            return True
        rx_min = IPR_RELAX_RX_MIN_DBM
        tx_min = IPR_RELAX_TX_MIN_DBM
        max_value = IPR_RELAX_MAX_DBM
    else:
        if not relax:
            return True
        rx_min = NON_IPR_RELAX_RX_MIN_DBM
        tx_min = NON_IPR_RELAX_TX_MIN_DBM
        max_value = NON_IPR_RELAX_MAX_DBM

    power_type = optics_power_type(row)
    measured = optics_measured_dbm(row)
    if not power_type or measured is None:
        return True
    if power_type == "RX":
        return measured < rx_min or measured > max_value
    if power_type == "TX":
        return measured < tx_min or measured > max_value
    return True


def t1_t0_detail_rows(
    details: Sequence[Dict[str, object]],
    targets: Sequence[str],
) -> List[Dict[str, object]]:
    target_filter = set(targets)
    rows: List[Dict[str, object]] = []

    for row in details:
        target = str(row.get("DG") or "").strip().upper()
        if target not in target_filter:
            continue

        issue_type = row.get("Issue Type")
        if issue_type == "Optics TX/RX":
            power_type = optics_power_type(row)
            output = {
                "Issue Type": "Optics",
                "Power Type": power_type,
                "PP Matched": has_pp(row),
            }
            output.update(row)
            output["Issue Type"] = "Optics"
            output["Power Type"] = power_type
            rows.append(output)
            continue

        if issue_type != "Combined FEC":
            continue

        if row.get("Counts Pre Fec") == 1:
            output = {
                "Issue Type": "Pre-FEC",
                "Power Type": "",
                "PP Matched": has_pp(row),
            }
            output.update(row)
            output["Issue Type"] = "Pre-FEC"
            output["Power Type"] = ""
            rows.append(output)

        if row.get("Counts Fec Bin") == 1:
            output = {
                "Issue Type": "FEC Bin",
                "Power Type": "",
                "PP Matched": has_pp(row),
            }
            output.update(row)
            output["Issue Type"] = "FEC Bin"
            output["Power Type"] = ""
            rows.append(output)

    return rows


def write_t1_t0_excel_report(
    path: Path,
    targets: Sequence[str],
    details: Sequence[Dict[str, object]],
) -> Path:
    try:
        from openpyxl import Workbook
    except ImportError as exc:
        raise RuntimeError("Writing workbook output requires openpyxl") from exc

    output_path = timestamped_path(path.expanduser())
    rows = t1_t0_detail_rows(details, targets)

    wb = Workbook()
    summary = wb.active
    summary.title = "Summary"
    used = {summary.title}
    summary.append(
        ["DG", "Racks", "Optics RX", "Optics TX", "Pre-FEC", "FEC Bin", "Total Issues", "PP Matched"]
    )

    for target in targets:
        target_rows = [row for row in rows if row.get("DG") == target]
        rx = sum(1 for row in target_rows if row.get("Issue Type") == "Optics" and row.get("Power Type") == "RX")
        tx = sum(1 for row in target_rows if row.get("Issue Type") == "Optics" and row.get("Power Type") == "TX")
        pre_fec = sum(1 for row in target_rows if row.get("Issue Type") == "Pre-FEC")
        fec_bin = sum(1 for row in target_rows if row.get("Issue Type") == "FEC Bin")
        summary.append(
            [
                target,
                ",".join(DG_RACKS.get(target, ())),
                rx,
                tx,
                pre_fec,
                fec_bin,
                rx + tx + pre_fec + fec_bin,
                sum(1 for row in target_rows if row.get("PP Matched")),
            ]
        )

    write_rows_sheet(
        wb,
        "Sources",
        ("Source File", "Source Sheet", "Issue Type", "Power Type", "Rows", "PP Matched"),
        (
            [
                source_file,
                source_sheet,
                issue_type,
                power_type,
                len(group_rows),
                sum(1 for row in group_rows if row.get("PP Matched")),
            ]
            for (source_file, source_sheet, issue_type, power_type), group_rows in sorted(
                group_rows_by(
                    rows,
                    ("Source File", "Source Sheet", "Issue Type", "Power Type"),
                ).items(),
                key=lambda item: tuple("" if value is None else str(value) for value in item[0]),
            )
        ),
        used,
    )
    write_detail_sheet(wb, "All", rows, used)
    write_detail_sheet(wb, "Optics", [row for row in rows if row.get("Issue Type") == "Optics"], used)
    write_detail_sheet(wb, "Pre-FEC", [row for row in rows if row.get("Issue Type") == "Pre-FEC"], used)
    write_detail_sheet(wb, "FEC Bin", [row for row in rows if row.get("Issue Type") == "FEC Bin"], used)
    write_rows_sheet(
        wb,
        "DG",
        ("DG", "Racks"),
        ((target, ",".join(DG_RACKS.get(target, ()))) for target in targets),
        used,
    )
    for target in targets:
        write_detail_sheet(wb, target, [row for row in rows if row.get("DG") == target], used)

    apply_style_template(
        wb,
        DEFAULT_T1_T0_STYLE_TEMPLATE,
        t1_t0_template_sheet_name,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output_path)
    return output_path


def group_rows_by(
    rows: Sequence[Dict[str, object]],
    keys: Sequence[str],
) -> Dict[Tuple[object, ...], List[Dict[str, object]]]:
    grouped: Dict[Tuple[object, ...], List[Dict[str, object]]] = defaultdict(list)
    for row in rows:
        grouped[tuple(row.get(key) for key in keys)].append(row)
    return dict(grouped)


def original_detail_rows(rows: Sequence[Dict[str, object]]) -> List[Dict[str, object]]:
    helper_columns = {
        "Source File",
        "Source Sheet",
        "DG",
        "Issue Type",
        "Counts Fec Bin",
        "Counts Pre Fec",
    }
    return [{key: value for key, value in row.items() if key not in helper_columns} for row in rows]


def write_combined_fec_by_dg_workbook(
    path: Path,
    targets: Sequence[str],
    details: Sequence[Dict[str, object]],
) -> Path:
    try:
        from openpyxl import Workbook
    except ImportError as exc:
        raise RuntimeError("Writing workbook output requires openpyxl") from exc

    output_path = timestamped_path(path.expanduser())
    wb = Workbook()
    default_sheet = wb.active
    wb.remove(default_sheet)
    used: set[str] = set()

    for target in targets:
        rows = [
            row
            for row in details
            if row.get("DG") == target and row.get("Issue Type") == "Combined FEC"
        ]
        write_detail_sheet(wb, f"{target}_combined_fec", original_detail_rows(rows), used)

    apply_style_template(
        wb,
        DEFAULT_COMBINED_FEC_STYLE_TEMPLATE,
        combined_fec_template_sheet_name,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output_path)
    return output_path


def write_excel_report(
    path: Path,
    current: Dict[str, Dict[str, int]],
    targets: Sequence[str],
    details: Sequence[Dict[str, object]],
) -> None:
    try:
        from openpyxl import Workbook
    except ImportError as exc:
        raise RuntimeError("Writing workbook output requires openpyxl") from exc

    output_path = path.expanduser()
    wb = Workbook()
    summary = wb.active
    summary.title = "Summary"
    used = {summary.title}
    summary.append(["DG", "Racks", *ISSUE_METRICS, "Total"])
    for target in targets:
        values = current.get(target, {})
        summary.append(
            [
                target,
                ",".join(DG_RACKS.get(target, ())),
                *(values.get(metric, 0) for metric in ISSUE_METRICS),
                values.get("Total", 0),
            ]
        )
    total_values = sum_metrics(*(current.get(target, empty_metric_counts()) for target in targets))
    summary.append(
        [
            "Total",
            "",
            *(total_values.get(metric, 0) for metric in ISSUE_METRICS),
            total_values.get("Total", 0),
        ]
    )

    write_rows_sheet(
        wb,
        "DG Racks",
        ("DG", "Racks"),
        ((target, ",".join(racks)) for target, racks in DG_RACKS.items()),
        used,
    )
    write_detail_sheet(wb, "All", details, used)
    for metric in ISSUE_METRICS:
        if metric == "Pre Fec":
            rows = [row for row in details if row.get("Counts Pre Fec") == 1]
        elif metric == "Fec Bin":
            rows = [row for row in details if row.get("Counts Fec Bin") == 1]
        else:
            rows = [row for row in details if row.get("Issue Type") == metric]
        write_detail_sheet(wb, metric, rows, used)

    for target in targets:
        write_detail_sheet(
            wb,
            target,
            [row for row in details if row.get("DG") == target],
            used,
        )
        write_detail_sheet(
            wb,
            f"{target}_combined_fec",
            [
                row
                for row in details
                if row.get("DG") == target and row.get("Issue Type") == "Combined FEC"
            ],
            used,
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output_path)


def read_t1_summary(
    paths: Sequence[Path],
    targets: Sequence[str],
    relax: bool = False,
    relax_ipr: bool = False,
) -> Dict[str, Dict[str, int]]:
    try:
        from openpyxl import load_workbook
    except ImportError as exc:
        raise RuntimeError("T1 report parsing requires openpyxl") from exc

    target_filter = set(targets)
    summary: Dict[str, Dict[str, int]] = defaultdict(lambda: {key: 0 for key in OPTICS_FEC_KEYS})

    for raw_path in paths:
        path = raw_path.expanduser()
        reject_t1_side_source_report(path, "--t1-report")
        if not path.exists():
            raise FileNotFoundError(path)
        wb = load_workbook(path, read_only=True, data_only=True)
        if "Summary" in wb.sheetnames:
            ws = wb["Summary"]
            rows = ws.iter_rows(values_only=True)
            try:
                header = [str(value).strip() if value is not None else "" for value in next(rows)]
            except StopIteration:
                continue
            dg_idx = find_column(header, ("DG", "Target"))
            rx_idx = find_column(header, ("Optics RX", "RX Optics", "RX"))
            tx_idx = find_column(header, ("Optics TX", "TX Optics", "TX"))
            prefec_idx = find_column(header, ("Pre-FEC", "Pre FEC", "PreFEC"))
            fecbin_idx = find_column(header, ("FEC Bin", "FEC BIN", "FECBin"))
            for row in rows:
                if dg_idx >= len(row) or row[dg_idx] is None:
                    continue
                raw_target = str(row[dg_idx]).strip()
                if normalize(raw_target) == "total":
                    continue
                try:
                    target = normalize_target(raw_target)
                except ValueError:
                    continue
                if target not in target_filter:
                    continue
                summary[target]["RX Optics"] += parse_int(row[rx_idx] or 0)
                summary[target]["TX Optics"] += parse_int(row[tx_idx] or 0)
                summary[target]["Pre-FEC"] += parse_int(row[prefec_idx] or 0)
                summary[target]["Fec Bin"] += parse_int(row[fecbin_idx] or 0)
            continue

        if "All" not in wb.sheetnames:
            continue
        ws = wb["All"]
        rows = ws.iter_rows(values_only=True)
        try:
            header = [str(value).strip() if value is not None else "" for value in next(rows)]
        except StopIteration:
            continue
        dg_idx = find_column(header, ("DG", "Target"))
        issue_idx = find_column(header, ("Issue Type",))
        power_idx = optional_column(header, ("Power Type",))
        for row in rows:
            if dg_idx >= len(row) or row[dg_idx] is None:
                continue
            raw_target = str(row[dg_idx]).strip()
            if normalize(raw_target) == "total":
                continue
            try:
                target = normalize_target(raw_target)
            except ValueError:
                continue
            if target not in target_filter:
                continue
            issue = normalize(row[issue_idx] if issue_idx < len(row) else "")
            power = normalize(row[power_idx] if power_idx is not None and power_idx < len(row) else "")
            row_data = row_dict(header, row)
            if issue == "optics" and power in {"rx", "tx"} and not optics_row_passes_relaxed_threshold(
                row_data,
                relax=relax,
                relax_ipr=relax_ipr,
            ):
                continue
            if issue == "optics" and power == "rx":
                summary[target]["RX Optics"] += 1
            elif issue == "optics" and power == "tx":
                summary[target]["TX Optics"] += 1
            elif issue == "prefec":
                summary[target]["Pre-FEC"] += 1
            elif issue == "fecbin":
                summary[target]["Fec Bin"] += 1

    return dict(summary)


def flatten_path_groups(groups: Sequence[Sequence[Path]] | None) -> List[Path]:
    paths: List[Path] = []
    for group in groups or []:
        paths.extend(group)
    return paths


def build_report(
    previous: Dict[str, Dict[str, int]],
    current: Dict[str, Dict[str, int]],
    targets: Sequence[str],
    t1_summary: Dict[str, Dict[str, int]] | None = None,
) -> str:
    target_rows = []
    all_targets = [*targets, TOTAL_TARGET]
    for target in all_targets:
        prev = previous[target]["Total"]
        cur = current[target]["Total"]
        target_rows.append([target, prev, cur, signed_int(cur - prev), progress(prev, cur)])

    sections = [
        "T0 <> T1:",
        "Target Total Summary",
        table(
            COMPARISON_HEADERS,
            target_rows,
            left_columns={0},
        ),
        "",
        "Issue Breakdown By Target",
    ]

    for target in targets:
        sections.extend(
            [
                "",
                target,
                table(
                    COMPARISON_HEADERS,
                    metric_rows(previous[target], current[target]),
                    left_columns={0},
                ),
            ]
        )

    sections.extend(
        [
            "",
            "Total Types Of Errors",
            table(
                COMPARISON_HEADERS,
                metric_rows(previous[TOTAL_TARGET], current[TOTAL_TARGET]),
                left_columns={0},
            ),
        ]
    )

    if t1_summary:
        sections.extend(
            [
                "",
                "T1 <> T0:",
                table(
                    ("DG", "RX Optics", "TX Optics", "FEC Bin", "Pre-FEC", "Grand Total"),
                    optics_fec_rows(t1_summary, targets),
                    left_columns={0},
                ),
            ]
        )

    return "\n".join(sections)


def read_block(label: str, sentinel: str) -> str:
    print(
        f"\nPaste {label}. Finish with a line containing only {sentinel!r}.",
        file=sys.stderr,
    )
    lines: List[str] = []
    while True:
        try:
            line = input()
        except EOFError as exc:
            raise SystemExit(f"Input ended before sentinel {sentinel!r} for {label}") from exc
        if line.strip() == sentinel:
            break
        lines.append(line)
    return "\n".join(lines)


def resolve_previous_path(path: Path | str | None) -> Path | None:
    if path is None:
        return None
    resolved = Path(path).expanduser()
    if not resolved.is_absolute():
        resolved = DEFAULT_DATA_DIR / resolved
    return resolved


def load_or_prompt(path: Path | str | None, label: str, sentinel: str, missing_ok: bool = False) -> str:
    if path:
        resolved = Path(path).expanduser()
        if missing_ok and not resolved.exists():
            return ""
        return resolved.read_text(encoding="utf-8")
    return read_block(label, sentinel)


def paths_match(left: Path, right: Path) -> bool:
    return left.expanduser().resolve() == right.expanduser().resolve()


def write_text_report(path: Path, report: str) -> Path:
    resolved = path.expanduser()
    resolved.parent.mkdir(parents=True, exist_ok=True)
    resolved.write_text(report + "\n", encoding="utf-8")
    return resolved


def write_text_outputs(report: str, output_path: Path | None, previous_path: Path | None) -> None:
    written_output = None
    if output_path:
        written_output = write_text_report(output_path, report)
        print(f"\nReport written to: {written_output}")

    if previous_path:
        if written_output is not None and paths_match(previous_path, written_output):
            written_previous = written_output
        else:
            written_previous = write_text_report(previous_path, report)
        print(f"\nPrevious report updated: {written_previous}")


def current_paths(args: argparse.Namespace) -> Dict[str, str]:
    paths: Dict[str, str] = {}

    for item in args.current or []:
        if "=" not in item:
            raise ValueError(f"Invalid --current value {item!r}; expected DG=path")
        target, path = item.split("=", 1)
        target = normalize_target(target)
        if not path:
            raise ValueError(f"Invalid --current value {item!r}; path is empty")
        paths[target] = path

    return paths


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a refreshed DG progress report from previous and current pasted outputs."
    )
    parser.add_argument(
        "full_report_arg",
        nargs="?",
        type=Path,
        help=(
            "Optional shortcut for --full-report: a single T0 full_report.xlsx generated "
            "by the combined DG qcli command."
        ),
    )
    parser.add_argument(
        "--previous",
        nargs="?",
        const=DEFAULT_PREVIOUS_REPORT,
        type=Path,
        help=(
            "Read the previous formatted report from this file and update it with "
            "the generated report. If no path is given, uses "
            f"{DEFAULT_PREVIOUS_REPORT}."
        ),
    )
    parser.add_argument(
        "--excel",
        action="append",
        nargs="+",
        type=Path,
        help=(
            "One or more T0 qcli *_full_report.xlsx files to use as the current "
            "T0 <> T1 input. Repeatable; rows are grouped by DG rack mapping."
        ),
    )
    parser.add_argument(
        "--full-report",
        type=Path,
        help=(
            "Single T0 full_report.xlsx generated by a combined DG qcli command. "
            "Requires --targets unless --previous can provide the target list."
        ),
    )
    parser.add_argument(
        "--print-qcli-command",
        action="store_true",
        help="Print the combined qcli hc-summary command(s) for --targets, then exit.",
    )
    parser.add_argument(
        "--t1-report",
        action="append",
        nargs="+",
        type=Path,
        help=(
            "Optional T1 <> T0 detail workbook(s), such as "
            "AGA5.2-DG9-10-15-16-...-with-pp.xlsx, used for the final T1 table. "
            "Do not pass individual T1-side RX/Pre-FEC/FEC-Bin *_full_report.xlsx files."
        ),
    )
    parser.add_argument(
        "--output-excel",
        type=Path,
        help="Write the grouped current workbook rows and split FEC sheets to this Excel file.",
    )
    parser.add_argument(
        "--t1-output-excel",
        type=Path,
        help=(
            "Write the split T1 <> T0 RX/TX optics, Pre-FEC, and FEC Bin workbook "
            "to this path. With --full-report, a timestamped path is generated by default."
        ),
    )
    parser.add_argument(
        "--combined-fec-output-excel",
        type=Path,
        help=(
            "Write a workbook containing one combined_fec sheet per DG to this path. "
            "With --full-report, a timestamped path is generated by default."
        ),
    )
    parser.add_argument(
        "--no-auto-excel",
        action="store_true",
        help="Do not write default Excel artifacts when --full-report is used.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Write the generated text report to this file as well as stdout.",
    )
    parser.add_argument(
        "--current",
        action="append",
        metavar="DG=PATH",
        help="Path to a current DG rack-level output, repeatable for any DG number",
    )
    parser.add_argument(
        "--targets",
        "--target",
        dest="targets",
        help=(
            "Comma-separated DG targets to process, for example 9,10,15,16,25,26. "
            "Use 'all' for every DG in the AGA5.2 rack map."
        ),
    )
    parser.add_argument(
        "--sentinel",
        default="END",
        help="Line used to finish each interactive paste block. Default: END",
    )
    parser.add_argument(
        "--optics-fec",
        action="append",
        metavar="DG=RX,TX,FECBIN,PRE",
        help="RX optics, TX optics, FEC BIN, and Pre-FEC counts for one DG. Repeatable.",
    )
    parser.add_argument(
        "--optics-fec-file",
        help="Path to a file containing DG RX/TX optics, FEC BIN, and Pre-FEC rows or table",
    )
    parser.add_argument(
        "--no-optics-fec-summary",
        action="store_true",
        help="Skip the final T1 <> T0 RX/TX optics and Pre-FEC summary table",
    )
    parser.add_argument(
        "--relax",
        action="store_true",
        help="Relax non-IPR optics RX/TX min/max thresholds by 1 dBm.",
    )
    parser.add_argument(
        "--relax-ipr",
        action="store_true",
        help="Relax IPR optics thresholds to RX -5..3 dBm and TX -3..3 dBm.",
    )
    parser.add_argument("--no-warnings", action="store_true", help="Suppress rack total mismatch warnings")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        full_report = args.full_report or args.full_report_arg
        if args.full_report and args.full_report_arg and args.full_report != args.full_report_arg:
            raise ValueError("Use either positional full_report.xlsx or --full-report, not both")
        previous_path = resolve_previous_path(args.previous)
        previous_text_from_path = ""
        if previous_path:
            previous_text_from_path = load_or_prompt(
                previous_path,
                "the previous formatted report",
                args.sentinel,
                missing_ok=True,
            )

        requested_targets = parse_target_list(args.targets)
        if requested_targets is None:
            if not previous_path:
                raise ValueError("--targets is required unless --previous is provided")
            requested_targets = discover_targets(previous_text_from_path.splitlines())
            if not requested_targets:
                raise ValueError(
                    "Could not infer --targets from --previous; "
                    "the previous report is missing or contains no DG sections"
                )
        targets = list(requested_targets)

        if args.print_qcli_command:
            print(combined_qcli_command(targets, args.relax))
            return 0

        excel_paths = flatten_path_groups(args.excel)
        if full_report:
            excel_paths.append(full_report)
        if excel_paths:
            previous: Dict[str, Dict[str, int]]
            previous_has_content = False
            if previous_path:
                previous_text = previous_text_from_path
                previous_has_content = bool(previous_text.strip())
                if previous_has_content:
                    previous, _previous_targets = previous_current_metrics(
                        previous_text,
                        requested_targets,
                        allow_missing=True,
                    )
                else:
                    previous = {}
            else:
                previous = {}

            current, _current_targets, details = read_excel_current(
                excel_paths,
                requested_targets,
                args.relax,
                args.relax_ipr,
            )
            targets = list(requested_targets)
            if not targets:
                raise ValueError("No DG rows matched the workbook input and rack mapping")

            fill_missing_previous_from_current(previous, current, targets)

            previous[TOTAL_TARGET] = sum_metrics(*(previous[target] for target in targets))
            current[TOTAL_TARGET] = sum_metrics(*(current[target] for target in targets))

            t1_summary = None
            t1_paths = flatten_path_groups(args.t1_report)
            if t1_paths and not args.no_optics_fec_summary:
                t1_summary = read_t1_summary(t1_paths, targets, args.relax, args.relax_ipr)

            report = build_report(previous, current, targets, t1_summary)
            print(report)

            write_text_outputs(report, args.output, previous_path)
            if args.output_excel:
                write_excel_report(args.output_excel, current, targets, details)
                print(f"\nExcel report written to: {args.output_excel.expanduser()}")

            auto_excel = bool(full_report) and not args.no_auto_excel
            default_dir = (
                full_report.expanduser().parent
                if full_report
                else DEFAULT_DATA_DIR
            )
            output_timestamp = datetime.now()

            if args.t1_output_excel or auto_excel:
                t1_output = args.t1_output_excel or default_t1_t0_output_path(
                    default_dir,
                    targets,
                    output_timestamp,
                )
                written_t1_output = write_t1_t0_excel_report(t1_output, targets, details)
                print(f"\nT1 <> T0 Excel report written to: {written_t1_output}")

            if args.combined_fec_output_excel or auto_excel:
                combined_fec_output = (
                    args.combined_fec_output_excel
                    or default_combined_fec_output_path(default_dir, output_timestamp)
                )
                written_combined_fec_output = write_combined_fec_by_dg_workbook(
                    combined_fec_output,
                    targets,
                    details,
                )
                print(
                    "\nCombined FEC by DG Excel report written to: "
                    f"{written_combined_fec_output}"
                )

            return 0

        if previous_path:
            previous_text = previous_text_from_path
        else:
            previous_text = load_or_prompt(
                previous_path,
                "the previous formatted report",
                args.sentinel,
                missing_ok=True,
            )
        first_report = not previous_text.strip()
        if first_report:
            previous = {}
        else:
            previous, _previous_targets = previous_current_metrics(
                previous_text,
                requested_targets,
                allow_missing=True,
            )
        targets = list(requested_targets)
        paths = current_paths(args)

        current: Dict[str, Dict[str, int]] = {}
        warnings: List[str] = []
        for position, target in enumerate(targets, start=1):
            text = load_or_prompt(
                paths.get(target),
                f"the current {target} output ({position} of {len(targets)})",
                args.sentinel,
            )
            current[target], target_warnings = parse_rack_rollup(text, target)
            warnings.extend(target_warnings)

        fill_missing_previous_from_current(previous, current, targets)

        previous[TOTAL_TARGET] = sum_metrics(*(previous[target] for target in targets))
        current[TOTAL_TARGET] = sum_metrics(*(current[target] for target in targets))
        t1_summary = optics_fec_counts(args, targets)

        report = build_report(previous, current, targets, t1_summary)
        print(report)

        write_text_outputs(report, args.output, previous_path)

        if warnings and not args.no_warnings:
            print("\nWarnings:", file=sys.stderr)
            for warning in warnings:
                print(f"- {warning}", file=sys.stderr)

    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
