#!/usr/bin/env python
# abderrahman.jouhari@oracle.com
# DOT1x bug validation - checks what interfaces do not have vlan assigned

from subprocess import Popen, PIPE
from os import getlogin
import pexpect
from pprint import pprint
import json
from sys import argv
from datetime import datetime


username = getlogin()  # get the system username
path = argv[1] # path to the file with your device list

output_file = f'/tmp/output_dot1x_validation_{str(datetime.now().time())}.json'

show_dot1x_success = "show dot1x hosts | no-more | grep -i 'SUCCESS' | grep -oh 'Et.*/.'"
show_hosts_vlan = "show vlan 100-4094 | json | no-more | grep -oh 'et.*/.'"

data = {}

def file_to_list(file):
    """
    :param file:
    phx1-j2-t1-r23-mgmt
    phx1-j2-t1-r23-mgmt
    phx1-j2-t1-r24-mgmt
    phx1-j2-t1-r24-mgmt
    :return: ['phx1-j2-t1-r23-mgmt', 'phx1-j2-t1-r24-mgmt', 'phx1-j2-t1-r25-mgmt']

    """
    openfile = open(file, 'r')
    hostnames = openfile.readlines()
    return hostnames

if __name__ == '__main__':
    """
    This script will run through a list of devices and check optics connected to the interfaces for firmware version
    version 
    Version 150 and 232 don't have to be upgraded. 
    """
    hostnames = file_to_list(path)
    # result = open(output_file, "w")
    #lines = []
    for hostname in hostnames:
        hostname = hostname.strip('\n').strip()
        print('#######', hostname)
        try:
            p = Popen(["jitpw", "-rqe", hostname], stdout=PIPE, stderr=PIPE, universal_newlines=True)
            output, errors = p.communicate()
        except:
            print("####### {}\njitpw failed.\nerror: {} \noutput: {}".format(errors, output, hostname))
        # clean the password generated by jitpw as it includes a '\n' character at the end. like: 'vSk5M?ZR^i1\n'
        password = output.strip('\n')
        try:
            child = pexpect.spawn("ssh {}@{}".format(username, hostname))
            i = child.expect(['[pP]assword:', r'yes/no'], timeout=60)

            if i == 0:
                child.sendline(password)
            elif i == 1:
                child.sendline('yes')
                child.expect('[pP]assword:', timeout=60)
                child.sendline(password)
            #print(child.before.decode("utf-8"))
            child.expect('#')
        except:
            print("ERROR - couldn't login to: {}".format(hostname))
            host = hostname + " couldn't login"
            data[hostname] = "can't login"
            #lines.append(host)
            continue

        child.sendline(show_dot1x_success)
        child.expect('#')  # match the prompt
        cmd_output = child.before.decode("utf-8")
        out = cmd_output.split("\n")[1:-1]
        auth_if = [i.rstrip().capitalize() for i in out]


        child.sendline(show_hosts_vlan)
        child.expect('#')  # match the prompt
        cmd_output = child.before.decode("utf-8")
        out = cmd_output.split("\n")[1:-1]
        vlan_assigned_if = [i.rstrip().capitalize() for i in out]
        data[hostname] = []
        for intf in auth_if:
            if intf not in vlan_assigned_if:
                print(hostname, intf, "not assigned VLAN")
                data[hostname].append(intf)

        if len(data[hostname]) == 0:
            del data[hostname]

        child.sendline('exit')
        child.expect('~*')
    pprint(data)
    json.dump(data, open(output_file, 'w'))

print(f"output file (json): {output_file}")